// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DatabaseStatistics module

	/**
	* Number of minutes between creation of snapshots.
	*/
	public static java.lang.Long getSnapshotInterval()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DatabaseStatistics.SnapshotInterval");
	}

	/**
	* Number of snapshots to retain in the database.
	* Note that each snapshot can contain up to 5000 records.
	*/
	public static java.lang.Long getSnapshotRetention()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DatabaseStatistics.SnapshotRetention");
	}
}