// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasestatistics.actions;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Function;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import databasestatistics.helpers.DbHelper;

public class IsPgStatStatementsEnabled extends CustomJavaAction<java.lang.Boolean>
{
	public IsPgStatStatementsEnabled(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Core.dataStorage().executeWithConnection(getContext(), isPgStatStatementsEnabled(getContext()));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsPgStatStatementsEnabled";
	}

	// BEGIN EXTRA CODE
	private Function<Connection, Boolean> isPgStatStatementsEnabled(IContext context) throws Exception {
		return connection ->
		{
			ResultSet rs = null;
			Statement stat = null;
			Boolean result = false;
			
			try {
				stat = connection.createStatement();
				rs = stat.executeQuery("SELECT * FROM information_schema.\"views\" v where table_name ='pg_stat_statements'");
				result = rs.next();
			} catch (SQLException e) {
				DbHelper.LOGGER.error("Unable to determine if pg_stat_statements is enabled: " + e.getMessage(), e);
			} finally {
				try { if (rs != null) rs.close(); } catch (Exception e) {}
				try { if (stat != null) stat.close(); } catch (Exception e) {}
			}
			return result;
		};
	}
	// END EXTRA CODE
}
