// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasestatistics.actions;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Function;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import databasestatistics.helpers.DbHelper;
import databasestatistics.proxies.StatisticsState;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PopulateStatisticsState extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __statisticsState;
	private databasestatistics.proxies.StatisticsState statisticsState;

	public PopulateStatisticsState(IContext context, IMendixObject statisticsState)
	{
		super(context);
		this.__statisticsState = statisticsState;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.statisticsState = __statisticsState == null ? null : databasestatistics.proxies.StatisticsState.initialize(getContext(), __statisticsState);

		// BEGIN USER CODE
		Core.dataStorage().executeWithConnection(getContext(), enrichStatisticsState(getContext(), statisticsState));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PopulateStatisticsState";
	}

	// BEGIN EXTRA CODE
	private Function<Connection, Void> enrichStatisticsState(IContext context, StatisticsState state) throws Exception {
		return connection ->
		{
			ResultSet rs = null;
			Statement stat = null;
			
			try {
				DatabaseMetaData dbMeta = connection.getMetaData();
				if (dbMeta.getDatabaseMajorVersion() < 14) {
					// pg_stat_statements is only available from version 14 and up
					state.setDeallocatedStatements(-1L);
					return null;
				}
				
				stat = connection.createStatement();
				rs = stat.executeQuery("SELECT dealloc, stats_reset FROM pg_stat_statements_info");
				rs.next();
				state.setDeallocatedStatements(rs.getLong(1));
				state.setLastReset(rs.getDate(2));
			} catch (SQLException e) {
				DbHelper.LOGGER.error("Unable to retrieve pg_stat_statements_info : " + e.getMessage(), e);
			} finally {
				try { if (rs != null) rs.close(); } catch (Exception e) {}
				try { if (stat != null) stat.close(); } catch (Exception e) {}
			}
			return null;
		};
	}
	// END EXTRA CODE
}
