// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasestatistics.actions;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Function;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import databasestatistics.helpers.DbHelper;

public class ResetPgStatStatements extends CustomJavaAction<java.lang.Void>
{
	public ResetPgStatStatements(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.dataStorage().executeWithConnection(getContext(), resetPgStatStatements(getContext()));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ResetPgStatStatements";
	}

	// BEGIN EXTRA CODE
	private Function<Connection, Boolean> resetPgStatStatements(IContext context) throws Exception {
		return connection ->
		{
			Statement stat = null;
			Boolean result = false;
			
			try {
				stat = connection.createStatement();
				stat.execute("SELECT pg_stat_statements_reset()");
			} catch (SQLException e) {
				DbHelper.LOGGER.error("Unable to disable pg_stat_statements: " + e.getMessage(), e);
			} finally {
				try { if (stat != null) stat.close(); } catch (Exception e) {}
			}
			return result;
		};
	}
	// END EXTRA CODE
}
