// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies;

public class Administration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject administrationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseStatistics.Administration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dummy("Dummy"),
		Administration_DatabaseInformation("DatabaseStatistics.Administration_DatabaseInformation"),
		Administration_StatisticsState("DatabaseStatistics.Administration_StatisticsState");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Administration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseStatistics.Administration"));
	}

	protected Administration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject administrationMendixObject)
	{
		if (administrationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseStatistics.Administration", administrationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseStatistics.Administration");

		this.administrationMendixObject = administrationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Administration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasestatistics.proxies.Administration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasestatistics.proxies.Administration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasestatistics.proxies.Administration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasestatistics.proxies.Administration(context, mendixObject);
	}

	public static databasestatistics.proxies.Administration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasestatistics.proxies.Administration.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy()
	{
		return getDummy(getContext());
	}

	/**
	 * @param context
	 * @return value of Dummy
	 */
	public final java.lang.String getDummy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dummy.toString());
	}

	/**
	 * Set value of Dummy
	 * @param dummy
	 */
	public final void setDummy(java.lang.String dummy)
	{
		setDummy(getContext(), dummy);
	}

	/**
	 * Set value of Dummy
	 * @param context
	 * @param dummy
	 */
	public final void setDummy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dummy)
	{
		getMendixObject().setValue(context, MemberNames.Dummy.toString(), dummy);
	}

	/**
	 * @return value of Administration_DatabaseInformation
	 */
	public final databasestatistics.proxies.DatabaseInformation getAdministration_DatabaseInformation() throws com.mendix.core.CoreException
	{
		return getAdministration_DatabaseInformation(getContext());
	}

	/**
	 * @param context
	 * @return value of Administration_DatabaseInformation
	 */
	public final databasestatistics.proxies.DatabaseInformation getAdministration_DatabaseInformation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasestatistics.proxies.DatabaseInformation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Administration_DatabaseInformation.toString());
		if (identifier != null)
			result = databasestatistics.proxies.DatabaseInformation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Administration_DatabaseInformation
	 * @param administration_databaseinformation
	 */
	public final void setAdministration_DatabaseInformation(databasestatistics.proxies.DatabaseInformation administration_databaseinformation)
	{
		setAdministration_DatabaseInformation(getContext(), administration_databaseinformation);
	}

	/**
	 * Set value of Administration_DatabaseInformation
	 * @param context
	 * @param administration_databaseinformation
	 */
	public final void setAdministration_DatabaseInformation(com.mendix.systemwideinterfaces.core.IContext context, databasestatistics.proxies.DatabaseInformation administration_databaseinformation)
	{
		if (administration_databaseinformation == null)
			getMendixObject().setValue(context, MemberNames.Administration_DatabaseInformation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Administration_DatabaseInformation.toString(), administration_databaseinformation.getMendixObject().getId());
	}

	/**
	 * @return value of Administration_StatisticsState
	 */
	public final databasestatistics.proxies.StatisticsState getAdministration_StatisticsState() throws com.mendix.core.CoreException
	{
		return getAdministration_StatisticsState(getContext());
	}

	/**
	 * @param context
	 * @return value of Administration_StatisticsState
	 */
	public final databasestatistics.proxies.StatisticsState getAdministration_StatisticsState(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasestatistics.proxies.StatisticsState result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Administration_StatisticsState.toString());
		if (identifier != null)
			result = databasestatistics.proxies.StatisticsState.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Administration_StatisticsState
	 * @param administration_statisticsstate
	 */
	public final void setAdministration_StatisticsState(databasestatistics.proxies.StatisticsState administration_statisticsstate)
	{
		setAdministration_StatisticsState(getContext(), administration_statisticsstate);
	}

	/**
	 * Set value of Administration_StatisticsState
	 * @param context
	 * @param administration_statisticsstate
	 */
	public final void setAdministration_StatisticsState(com.mendix.systemwideinterfaces.core.IContext context, databasestatistics.proxies.StatisticsState administration_statisticsstate)
	{
		if (administration_statisticsstate == null)
			getMendixObject().setValue(context, MemberNames.Administration_StatisticsState.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Administration_StatisticsState.toString(), administration_statisticsstate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return administrationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasestatistics.proxies.Administration that = (databasestatistics.proxies.Administration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseStatistics.Administration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
