// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies;

public class Singleton
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject singletonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseStatistics.Singleton";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LastSnapshot("LastSnapshot"),
		IsAutoSnapshotEnabled("IsAutoSnapshotEnabled");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Singleton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseStatistics.Singleton"));
	}

	protected Singleton(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject singletonMendixObject)
	{
		if (singletonMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseStatistics.Singleton", singletonMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseStatistics.Singleton");

		this.singletonMendixObject = singletonMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Singleton.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasestatistics.proxies.Singleton initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasestatistics.proxies.Singleton.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasestatistics.proxies.Singleton initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasestatistics.proxies.Singleton(context, mendixObject);
	}

	public static databasestatistics.proxies.Singleton load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasestatistics.proxies.Singleton.initialize(context, mendixObject);
	}

	public static java.util.List<databasestatistics.proxies.Singleton> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasestatistics.proxies.Singleton> result = new java.util.ArrayList<databasestatistics.proxies.Singleton>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseStatistics.Singleton" + xpathConstraint))
			result.add(databasestatistics.proxies.Singleton.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LastSnapshot
	 */
	public final java.util.Date getLastSnapshot()
	{
		return getLastSnapshot(getContext());
	}

	/**
	 * @param context
	 * @return value of LastSnapshot
	 */
	public final java.util.Date getLastSnapshot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastSnapshot.toString());
	}

	/**
	 * Set value of LastSnapshot
	 * @param lastsnapshot
	 */
	public final void setLastSnapshot(java.util.Date lastsnapshot)
	{
		setLastSnapshot(getContext(), lastsnapshot);
	}

	/**
	 * Set value of LastSnapshot
	 * @param context
	 * @param lastsnapshot
	 */
	public final void setLastSnapshot(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastsnapshot)
	{
		getMendixObject().setValue(context, MemberNames.LastSnapshot.toString(), lastsnapshot);
	}

	/**
	 * @return value of IsAutoSnapshotEnabled
	 */
	public final java.lang.Boolean getIsAutoSnapshotEnabled()
	{
		return getIsAutoSnapshotEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAutoSnapshotEnabled
	 */
	public final java.lang.Boolean getIsAutoSnapshotEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAutoSnapshotEnabled.toString());
	}

	/**
	 * Set value of IsAutoSnapshotEnabled
	 * @param isautosnapshotenabled
	 */
	public final void setIsAutoSnapshotEnabled(java.lang.Boolean isautosnapshotenabled)
	{
		setIsAutoSnapshotEnabled(getContext(), isautosnapshotenabled);
	}

	/**
	 * Set value of IsAutoSnapshotEnabled
	 * @param context
	 * @param isautosnapshotenabled
	 */
	public final void setIsAutoSnapshotEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isautosnapshotenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsAutoSnapshotEnabled.toString(), isautosnapshotenabled);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return singletonMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasestatistics.proxies.Singleton that = (databasestatistics.proxies.Singleton) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseStatistics.Singleton";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
