// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies;

public class Snapshot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject snapshotMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseStatistics.Snapshot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreatedAt("CreatedAt"),
		Trigger("Trigger"),
		DeallocatedStatements("DeallocatedStatements");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Snapshot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseStatistics.Snapshot"));
	}

	protected Snapshot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject snapshotMendixObject)
	{
		if (snapshotMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseStatistics.Snapshot", snapshotMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseStatistics.Snapshot");

		this.snapshotMendixObject = snapshotMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Snapshot.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasestatistics.proxies.Snapshot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasestatistics.proxies.Snapshot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasestatistics.proxies.Snapshot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasestatistics.proxies.Snapshot(context, mendixObject);
	}

	public static databasestatistics.proxies.Snapshot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasestatistics.proxies.Snapshot.initialize(context, mendixObject);
	}

	public static java.util.List<databasestatistics.proxies.Snapshot> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasestatistics.proxies.Snapshot> result = new java.util.ArrayList<databasestatistics.proxies.Snapshot>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseStatistics.Snapshot" + xpathConstraint))
			result.add(databasestatistics.proxies.Snapshot.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.util.Date createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * Set value of Trigger
	 * @param trigger
	 */
	public final databasestatistics.proxies.Trigger getTrigger()
	{
		return getTrigger(getContext());
	}

	/**
	 * @param context
	 * @return value of Trigger
	 */
	public final databasestatistics.proxies.Trigger getTrigger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Trigger.toString());
		if (obj == null)
			return null;

		return databasestatistics.proxies.Trigger.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Trigger
	 * @param trigger
	 */
	public final void setTrigger(databasestatistics.proxies.Trigger trigger)
	{
		setTrigger(getContext(), trigger);
	}

	/**
	 * Set value of Trigger
	 * @param context
	 * @param trigger
	 */
	public final void setTrigger(com.mendix.systemwideinterfaces.core.IContext context, databasestatistics.proxies.Trigger trigger)
	{
		if (trigger != null)
			getMendixObject().setValue(context, MemberNames.Trigger.toString(), trigger.toString());
		else
			getMendixObject().setValue(context, MemberNames.Trigger.toString(), null);
	}

	/**
	 * @return value of DeallocatedStatements
	 */
	public final java.lang.Long getDeallocatedStatements()
	{
		return getDeallocatedStatements(getContext());
	}

	/**
	 * @param context
	 * @return value of DeallocatedStatements
	 */
	public final java.lang.Long getDeallocatedStatements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.DeallocatedStatements.toString());
	}

	/**
	 * Set value of DeallocatedStatements
	 * @param deallocatedstatements
	 */
	public final void setDeallocatedStatements(java.lang.Long deallocatedstatements)
	{
		setDeallocatedStatements(getContext(), deallocatedstatements);
	}

	/**
	 * Set value of DeallocatedStatements
	 * @param context
	 * @param deallocatedstatements
	 */
	public final void setDeallocatedStatements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long deallocatedstatements)
	{
		getMendixObject().setValue(context, MemberNames.DeallocatedStatements.toString(), deallocatedstatements);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return snapshotMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasestatistics.proxies.Snapshot that = (databasestatistics.proxies.Snapshot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseStatistics.Snapshot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
