// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies;

public class StatisticsState
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject statisticsStateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseStatistics.StatisticsState";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsEnabled("IsEnabled"),
		DeallocatedStatements("DeallocatedStatements"),
		LastReset("LastReset"),
		Administration_StatisticsState("DatabaseStatistics.Administration_StatisticsState");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StatisticsState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseStatistics.StatisticsState"));
	}

	protected StatisticsState(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject statisticsStateMendixObject)
	{
		if (statisticsStateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseStatistics.StatisticsState", statisticsStateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseStatistics.StatisticsState");

		this.statisticsStateMendixObject = statisticsStateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StatisticsState.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasestatistics.proxies.StatisticsState initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasestatistics.proxies.StatisticsState.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasestatistics.proxies.StatisticsState initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasestatistics.proxies.StatisticsState(context, mendixObject);
	}

	public static databasestatistics.proxies.StatisticsState load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasestatistics.proxies.StatisticsState.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled()
	{
		return getIsEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnabled
	 */
	public final java.lang.Boolean getIsEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnabled.toString());
	}

	/**
	 * Set value of IsEnabled
	 * @param isenabled
	 */
	public final void setIsEnabled(java.lang.Boolean isenabled)
	{
		setIsEnabled(getContext(), isenabled);
	}

	/**
	 * Set value of IsEnabled
	 * @param context
	 * @param isenabled
	 */
	public final void setIsEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenabled)
	{
		getMendixObject().setValue(context, MemberNames.IsEnabled.toString(), isenabled);
	}

	/**
	 * @return value of DeallocatedStatements
	 */
	public final java.lang.Long getDeallocatedStatements()
	{
		return getDeallocatedStatements(getContext());
	}

	/**
	 * @param context
	 * @return value of DeallocatedStatements
	 */
	public final java.lang.Long getDeallocatedStatements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.DeallocatedStatements.toString());
	}

	/**
	 * Set value of DeallocatedStatements
	 * @param deallocatedstatements
	 */
	public final void setDeallocatedStatements(java.lang.Long deallocatedstatements)
	{
		setDeallocatedStatements(getContext(), deallocatedstatements);
	}

	/**
	 * Set value of DeallocatedStatements
	 * @param context
	 * @param deallocatedstatements
	 */
	public final void setDeallocatedStatements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long deallocatedstatements)
	{
		getMendixObject().setValue(context, MemberNames.DeallocatedStatements.toString(), deallocatedstatements);
	}

	/**
	 * @return value of LastReset
	 */
	public final java.util.Date getLastReset()
	{
		return getLastReset(getContext());
	}

	/**
	 * @param context
	 * @return value of LastReset
	 */
	public final java.util.Date getLastReset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastReset.toString());
	}

	/**
	 * Set value of LastReset
	 * @param lastreset
	 */
	public final void setLastReset(java.util.Date lastreset)
	{
		setLastReset(getContext(), lastreset);
	}

	/**
	 * Set value of LastReset
	 * @param context
	 * @param lastreset
	 */
	public final void setLastReset(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastreset)
	{
		getMendixObject().setValue(context, MemberNames.LastReset.toString(), lastreset);
	}

	/**
	 * @return value of Administration_StatisticsState
	 */
	public final databasestatistics.proxies.Administration getAdministration_StatisticsState() throws com.mendix.core.CoreException
	{
		return getAdministration_StatisticsState(getContext());
	}

	/**
	 * @param context
	 * @return value of Administration_StatisticsState
	 */
	public final databasestatistics.proxies.Administration getAdministration_StatisticsState(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasestatistics.proxies.Administration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Administration_StatisticsState.toString());
		if (identifier != null)
			result = databasestatistics.proxies.Administration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Administration_StatisticsState
	 * @param administration_statisticsstate
	 */
	public final void setAdministration_StatisticsState(databasestatistics.proxies.Administration administration_statisticsstate)
	{
		setAdministration_StatisticsState(getContext(), administration_statisticsstate);
	}

	/**
	 * Set value of Administration_StatisticsState
	 * @param context
	 * @param administration_statisticsstate
	 */
	public final void setAdministration_StatisticsState(com.mendix.systemwideinterfaces.core.IContext context, databasestatistics.proxies.Administration administration_statisticsstate)
	{
		if (administration_statisticsstate == null)
			getMendixObject().setValue(context, MemberNames.Administration_StatisticsState.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Administration_StatisticsState.toString(), administration_statisticsstate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return statisticsStateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasestatistics.proxies.StatisticsState that = (databasestatistics.proxies.StatisticsState) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseStatistics.StatisticsState";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
