// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies;

public class Statement
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject statementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseStatistics.Statement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QueryId("QueryId"),
		Query("Query"),
		Calls("Calls"),
		TotalTimeSpentExecutingMs("TotalTimeSpentExecutingMs"),
		MinimumTimeSpentExecutingMs("MinimumTimeSpentExecutingMs"),
		MaximumTimeSpentExecutingMs("MaximumTimeSpentExecutingMs"),
		MeanTimeSpentExecutingMs("MeanTimeSpentExecutingMs"),
		Rows("Rows"),
		Statement_Snapshot("DatabaseStatistics.Statement_Snapshot");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Statement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseStatistics.Statement"));
	}

	protected Statement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject statementMendixObject)
	{
		if (statementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseStatistics.Statement", statementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseStatistics.Statement");

		this.statementMendixObject = statementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Statement.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databasestatistics.proxies.Statement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasestatistics.proxies.Statement.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static databasestatistics.proxies.Statement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasestatistics.proxies.Statement(context, mendixObject);
	}

	public static databasestatistics.proxies.Statement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasestatistics.proxies.Statement.initialize(context, mendixObject);
	}

	public static java.util.List<databasestatistics.proxies.Statement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasestatistics.proxies.Statement> result = new java.util.ArrayList<databasestatistics.proxies.Statement>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseStatistics.Statement" + xpathConstraint))
			result.add(databasestatistics.proxies.Statement.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of QueryId
	 */
	public final java.lang.Long getQueryId()
	{
		return getQueryId(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryId
	 */
	public final java.lang.Long getQueryId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.QueryId.toString());
	}

	/**
	 * Set value of QueryId
	 * @param queryid
	 */
	public final void setQueryId(java.lang.Long queryid)
	{
		setQueryId(getContext(), queryid);
	}

	/**
	 * Set value of QueryId
	 * @param context
	 * @param queryid
	 */
	public final void setQueryId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long queryid)
	{
		getMendixObject().setValue(context, MemberNames.QueryId.toString(), queryid);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Calls
	 */
	public final java.lang.Long getCalls()
	{
		return getCalls(getContext());
	}

	/**
	 * @param context
	 * @return value of Calls
	 */
	public final java.lang.Long getCalls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Calls.toString());
	}

	/**
	 * Set value of Calls
	 * @param calls
	 */
	public final void setCalls(java.lang.Long calls)
	{
		setCalls(getContext(), calls);
	}

	/**
	 * Set value of Calls
	 * @param context
	 * @param calls
	 */
	public final void setCalls(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long calls)
	{
		getMendixObject().setValue(context, MemberNames.Calls.toString(), calls);
	}

	/**
	 * @return value of TotalTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getTotalTimeSpentExecutingMs()
	{
		return getTotalTimeSpentExecutingMs(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getTotalTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalTimeSpentExecutingMs.toString());
	}

	/**
	 * Set value of TotalTimeSpentExecutingMs
	 * @param totaltimespentexecutingms
	 */
	public final void setTotalTimeSpentExecutingMs(java.math.BigDecimal totaltimespentexecutingms)
	{
		setTotalTimeSpentExecutingMs(getContext(), totaltimespentexecutingms);
	}

	/**
	 * Set value of TotalTimeSpentExecutingMs
	 * @param context
	 * @param totaltimespentexecutingms
	 */
	public final void setTotalTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totaltimespentexecutingms)
	{
		getMendixObject().setValue(context, MemberNames.TotalTimeSpentExecutingMs.toString(), totaltimespentexecutingms);
	}

	/**
	 * @return value of MinimumTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMinimumTimeSpentExecutingMs()
	{
		return getMinimumTimeSpentExecutingMs(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMinimumTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinimumTimeSpentExecutingMs.toString());
	}

	/**
	 * Set value of MinimumTimeSpentExecutingMs
	 * @param minimumtimespentexecutingms
	 */
	public final void setMinimumTimeSpentExecutingMs(java.math.BigDecimal minimumtimespentexecutingms)
	{
		setMinimumTimeSpentExecutingMs(getContext(), minimumtimespentexecutingms);
	}

	/**
	 * Set value of MinimumTimeSpentExecutingMs
	 * @param context
	 * @param minimumtimespentexecutingms
	 */
	public final void setMinimumTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minimumtimespentexecutingms)
	{
		getMendixObject().setValue(context, MemberNames.MinimumTimeSpentExecutingMs.toString(), minimumtimespentexecutingms);
	}

	/**
	 * @return value of MaximumTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMaximumTimeSpentExecutingMs()
	{
		return getMaximumTimeSpentExecutingMs(getContext());
	}

	/**
	 * @param context
	 * @return value of MaximumTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMaximumTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaximumTimeSpentExecutingMs.toString());
	}

	/**
	 * Set value of MaximumTimeSpentExecutingMs
	 * @param maximumtimespentexecutingms
	 */
	public final void setMaximumTimeSpentExecutingMs(java.math.BigDecimal maximumtimespentexecutingms)
	{
		setMaximumTimeSpentExecutingMs(getContext(), maximumtimespentexecutingms);
	}

	/**
	 * Set value of MaximumTimeSpentExecutingMs
	 * @param context
	 * @param maximumtimespentexecutingms
	 */
	public final void setMaximumTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal maximumtimespentexecutingms)
	{
		getMendixObject().setValue(context, MemberNames.MaximumTimeSpentExecutingMs.toString(), maximumtimespentexecutingms);
	}

	/**
	 * @return value of MeanTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMeanTimeSpentExecutingMs()
	{
		return getMeanTimeSpentExecutingMs(getContext());
	}

	/**
	 * @param context
	 * @return value of MeanTimeSpentExecutingMs
	 */
	public final java.math.BigDecimal getMeanTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MeanTimeSpentExecutingMs.toString());
	}

	/**
	 * Set value of MeanTimeSpentExecutingMs
	 * @param meantimespentexecutingms
	 */
	public final void setMeanTimeSpentExecutingMs(java.math.BigDecimal meantimespentexecutingms)
	{
		setMeanTimeSpentExecutingMs(getContext(), meantimespentexecutingms);
	}

	/**
	 * Set value of MeanTimeSpentExecutingMs
	 * @param context
	 * @param meantimespentexecutingms
	 */
	public final void setMeanTimeSpentExecutingMs(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal meantimespentexecutingms)
	{
		getMendixObject().setValue(context, MemberNames.MeanTimeSpentExecutingMs.toString(), meantimespentexecutingms);
	}

	/**
	 * @return value of Rows
	 */
	public final java.lang.Long getRows()
	{
		return getRows(getContext());
	}

	/**
	 * @param context
	 * @return value of Rows
	 */
	public final java.lang.Long getRows(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Rows.toString());
	}

	/**
	 * Set value of Rows
	 * @param rows
	 */
	public final void setRows(java.lang.Long rows)
	{
		setRows(getContext(), rows);
	}

	/**
	 * Set value of Rows
	 * @param context
	 * @param rows
	 */
	public final void setRows(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long rows)
	{
		getMendixObject().setValue(context, MemberNames.Rows.toString(), rows);
	}

	/**
	 * @return value of Statement_Snapshot
	 */
	public final databasestatistics.proxies.Snapshot getStatement_Snapshot() throws com.mendix.core.CoreException
	{
		return getStatement_Snapshot(getContext());
	}

	/**
	 * @param context
	 * @return value of Statement_Snapshot
	 */
	public final databasestatistics.proxies.Snapshot getStatement_Snapshot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasestatistics.proxies.Snapshot result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Statement_Snapshot.toString());
		if (identifier != null)
			result = databasestatistics.proxies.Snapshot.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Statement_Snapshot
	 * @param statement_snapshot
	 */
	public final void setStatement_Snapshot(databasestatistics.proxies.Snapshot statement_snapshot)
	{
		setStatement_Snapshot(getContext(), statement_snapshot);
	}

	/**
	 * Set value of Statement_Snapshot
	 * @param context
	 * @param statement_snapshot
	 */
	public final void setStatement_Snapshot(com.mendix.systemwideinterfaces.core.IContext context, databasestatistics.proxies.Snapshot statement_snapshot)
	{
		if (statement_snapshot == null)
			getMendixObject().setValue(context, MemberNames.Statement_Snapshot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Statement_Snapshot.toString(), statement_snapshot.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return statementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasestatistics.proxies.Statement that = (databasestatistics.proxies.Statement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseStatistics.Statement";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
