// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasestatistics.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DatabaseStatistics module
	public static void aCT_CreateSnapshot(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseStatistics.ACT_CreateSnapshot").withParams(params).execute(context);
	}
	public static void aCT_DisableStatistics(IContext context, databasestatistics.proxies.Administration _administration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Administration", _administration == null ? null : _administration.getMendixObject());
		Core.microflowCall("DatabaseStatistics.ACT_DisableStatistics").withParams(params).execute(context);
	}
	public static void aCT_EnableStatistics(IContext context, databasestatistics.proxies.Administration _administration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Administration", _administration == null ? null : _administration.getMendixObject());
		Core.microflowCall("DatabaseStatistics.ACT_EnableStatistics").withParams(params).execute(context);
	}
	public static void aCT_ResetStatistics(IContext context, databasestatistics.proxies.Administration _administration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Administration", _administration == null ? null : _administration.getMendixObject());
		Core.microflowCall("DatabaseStatistics.ACT_ResetStatistics").withParams(params).execute(context);
	}
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("DatabaseStatistics.AfterStartup").withParams(params).execute(context);
	}
	public static databasestatistics.proxies.Administration dS_GetAdministration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.DS_GetAdministration").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.Administration.initialize(context, result);
	}
	public static databasestatistics.proxies.DatabaseInformation dS_GetDatabaseInformation(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.DS_GetDatabaseInformation").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.DatabaseInformation.initialize(context, result);
	}
	public static databasestatistics.proxies.Singleton dS_GetSingleton(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.DS_GetSingleton").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.Singleton.initialize(context, result);
	}
	public static databasestatistics.proxies.StatisticsState dS_GetStatisticsState(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.DS_GetStatisticsState").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.StatisticsState.initialize(context, result);
	}
	public static void pG_DisableStatistics(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseStatistics.PG_DisableStatistics").withParams(params).execute(context);
	}
	public static void pG_EnableStatistics(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseStatistics.PG_EnableStatistics").withParams(params).execute(context);
	}
	public static databasestatistics.proxies.StatisticsState pG_GetStatisticsState(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.PG_GetStatisticsState").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.StatisticsState.initialize(context, result);
	}
	public static void sE_CleanupOldSnapshots(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseStatistics.SE_CleanupOldSnapshots").withParams(params).execute(context);
	}
	public static void sE_CreateAutomaticSnapshots(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatabaseStatistics.SE_CreateAutomaticSnapshots").withParams(params).execute(context);
	}
	public static databasestatistics.proxies.Snapshot sUB_CreateSnapshot(IContext context, databasestatistics.proxies.Trigger _trigger)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Trigger", _trigger == null ? null : _trigger.name());
		IMendixObject result = (IMendixObject)Core.microflowCall("DatabaseStatistics.SUB_CreateSnapshot").withParams(params).execute(context);
		return result == null ? null : databasestatistics.proxies.Snapshot.initialize(context, result);
	}
	public static void sUB_RefreshState(IContext context, databasestatistics.proxies.Administration _administration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Administration", _administration == null ? null : _administration.getMendixObject());
		Core.microflowCall("DatabaseStatistics.SUB_RefreshState").withParams(params).execute(context);
	}
}